name: "rpc-env"
description: "Iterates over the supported chain ids and sets the corresponding env var"
inputs:
  ALCHEMY_API_KEY:
    description: "Alchemy API key"
    required: false
  QUICKNODE_TOKEN:
    description: "Quicknode token"
    required: false
  QUICKNODE_ENDPOINT_NAME:
    description: "Quicknode endpoint name"
    required: false

runs:
  using: "node20"
  main: dist/action.js
