on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

## require that test.yml ran

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releaseCreated: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4.3.0
        id: release
        with:
          release-type: node
